## Importamos las Librerías:

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, balanced_accuracy_score, classification_report, f1_score
from imblearn.over_sampling import SMOTE
import statsmodels.api as sm
import pyarrow
from scipy.stats import chi2
import warnings
warnings.filterwarnings('ignore')

## Establecemos los Parámetros de los Gráficos:

In [3]:
sns.set_style("white")
sns.set_context("notebook")
plt.rcParams.update({
    'font.family': 'serif',
    'mathtext.fontset': 'stix',
    'font.serif': 'Times New Roman',
    'figure.figsize': (11, 9.4),
    'axes.edgecolor': 'white',
    'axes.labelcolor': '#333333',
    'axes.titlesize': 20,
    'axes.titlecolor': '#333333',
    'xtick.color': '#333333',
    'ytick.color': '#333333',
    'axes.labelsize': 14,
    'xtick.labelsize': 12,
    'ytick.labelsize': 12
})

## Cargamos el Conjunto de Datos:

In [4]:
data = pd.read_csv('~/homicidios/data/final/homicidios_final.csv', dtype_backend='pyarrow')
data

,ent_regis,ent_resid,tloc_ocurr,causa_def,cod_adicio,lista_mex,sexo,afromex,conindig,lengua,...,area_ur,edad_agru,complicaro,dia_cert,mes_cert,anio_cert,maternas,razon_m,estado_defuncion_registrada,estado_defuncion_residencia
0,1,32,500 000 a 999 999 habitantes,"Neumonía, no especificada",NaN,Neumonía,Mujer,No,No,No,...,Urbana,De 70 a 74 años,No especificada,Dieciocho días,Diciembre,2022,NaN,NaN,Aguascalientes,Zacatecas
1,1,1,500 000 a 999 999 habitantes,Síndrome de dificultad respiratoria del adulto,NaN,Las demás enfermedades del aparato respiratorio,Mujer,No,No,No,...,Urbana,De 75 a 79 años,No especificada,Doce días,Diciembre,2022,NaN,NaN,Aguascalientes,Aguascalientes
2,1,1,500 000 a 999 999 habitantes,Enfermedad pulmonar obstructiva crónica con in...,NaN,Enfermedades pulmonares obstructivas crónicas,Mujer,No,No,No,...,Urbana,De 65 a 69 años,No especificada,Diecisiete días,Diciembre,2022,NaN,NaN,Aguascalientes,Aguascalientes
3,1,1,500 000 a 999 999 habitantes,Desnutrición proteicocalórica leve,NaN,Otras desnutriciones proteinocalóricas,Mujer,No,No,No,...,Urbana,De 90 a 94 años,No especificada,Un día,Enero,2023,NaN,NaN,Aguascalientes,Aguascalientes
4,1,14,500 000 a 999 999 habitantes,Cirrosis hepática alcohólica,NaN,Enfermedad alcohólica del hígado,Hombre,No,No,No,...,Rural,De 45 a 49 años,No aplica,Veintidós días,Diciembre,2022,NaN,NaN,Aguascalientes,Jalisco
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799864,32,32,20 000 a 29 999 habitantes,"Síndrome de aspiración neonatal, sin otra espe...",NaN,Dificultad respiratoria del recién nacido y ot...,Mujer,No,No,No aplica a menores de 3 años,...,Urbana,Menores de un año,No aplica,No especificado,Diciembre,2023,NaN,NaN,Zacatecas,Zacatecas
799865,32,32,100 000 a 249 999 habitantes,"Kernicterus, no especificado",NaN,Las demás afecciones originadas en el período ...,Mujer,No,No,No aplica a menores de 3 años,...,Urbana,Menores de un año,No aplica,Cinco días,Junio,2023,NaN,NaN,Zacatecas,Zacatecas
799866,32,32,100 000 a 249 999 habitantes,Síndrome de dificultad respiratoria del recién...,NaN,Dificultad respiratoria del recién nacido y ot...,Mujer,No,No,No aplica a menores de 3 años,...,Urbana,Menores de un año,No aplica,Nueve días,Agosto,2023,NaN,NaN,Zacatecas,Zacatecas
799867,32,32,100 000 a 249 999 habitantes,Gastrosquisis,NaN,Otras malformaciones congénitas y deformidades...,Mujer,No,No,No aplica a menores de 3 años,...,Urbana,Menores de un año,No aplica,Diecinueve días,Septiembre,2023,NaN,NaN,Zacatecas,Zacatecas
799868,32,32,5 000 a 9 999 habitantes,Insuficiencia respiratoria del recién nacido,NaN,Dificultad respiratoria del recién nacido y ot...,Hombre,No,No,No aplica a menores de 3 años,...,Rural,Menores de un año,No aplica,Seis días,Abril,2023,NaN,NaN,Zacatecas,Zacatecas

In [6]:
data.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 799869 entries, 0 to 799868
Data columns (total 62 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   ent_regis                    799869 non-null  int64
 1   ent_resid                    799869 non-null  int64
 2   tloc_ocurr                   799869 non-null  object
 3   causa_def                    799869 non-null  object
 4   cod_adicio                   85258 non-null   object
 5   lista_mex                    793731 non-null  object
 6   sexo                         799869 non-null  object
 7   afromex                      799869 non-null  object
 8   conindig                     799869 non-null  object
 9   lengua                       799869 non-null  object
 10  cve_lengua                   799869 non-null  object
 11  nacionalid                   799869 non-null  object
 12  nacesp_cve                   799869 non-null  object
 13  edad                         799869 non-null  object
 14  sem_gest                     799869 non-null  object
 15  gramos                       0 non-null       float64
 16  dia_ocurr                    799869 non-null  int64
 17  mes_ocurr                    799869 non-null  int64
 18  anio_ocur                    799869 non-null  int64
 19  dia_regis                    799869 non-null  int64
 20  mes_regis                    799869 non-null  int64
 21  anio_regis                   799869 non-null  int64
 22  dia_nacim                    799869 non-null  int64
 23  mes_nacim                    799869 non-null  object
 24  anio_nacim                   799869 non-null  int64
 25  cond_act                     799869 non-null  object
 26  ocupacion                    799869 non-null  object
 27  escolarida                   799869 non-null  object
 28  edo_civil                    799869 non-null  object
 29  tipo_defun                   799869 non-null  object
 30  ocurr_trab                   799869 non-null  object
 31  lugar_ocur                   799869 non-null  object
 32  par_agre                     799869 non-null  object
 33  vio_fami                     799869 non-null  object
 34  asist_medi                   799869 non-null  object
 35  cirugia                      799869 non-null  object
 36  natviole                     799869 non-null  object
 37  necropsia                    799869 non-null  object
 38  usonecrops                   799869 non-null  object
 39  encefalica                   799869 non-null  object
 40  donador                      799869 non-null  object
 41  sitio_ocur                   799869 non-null  object
 42  cond_cert                    799869 non-null  object
 43  derechohab                   799869 non-null  object
 44  embarazo                     799869 non-null  object
 45  rel_emba                     799869 non-null  object
 46  horas                        799869 non-null  object
 47  minutos                      799869 non-null  object
 48  capitulo                     799869 non-null  object
 49  grupo                        741886 non-null  object
 50  lista1                       799869 non-null  object
 51  gr_lismex                    84118 non-null   object
 52  area_ur                      799869 non-null  object
 53  edad_agru                    799869 non-null  object
 54  complicaro                   799869 non-null  object
 55  dia_cert                     799869 non-null  object
 56  mes_cert                     799869 non-null  object
 57  anio_cert                    799869 non-null  int64
 58  maternas                     774 non-null     object
 59  razon_m                      0 non-null       float64
 60  estado_defuncion_registrada  799869 non-null  object
 61  estado_defuncion_residencia  788830 non-null  object
dtypes: float64(2), int64(11), object(49)
memory usage: 2.9 GB

## Enraizamos el Proyecto:

In [11]:
import sys, os
sys.path.append(os.path.abspath(".."))

%load_ext autoreload
%autoreload 2

## Importamos las Funciones Modulares:

In [12]:
import modules.sustituir_nulos
from modules.sustituir_nulos import sustituir_nulos_pd
from modules.eliminar_variables import eliminar_variables_pd
from modules.eliminar_variables import variables_ml

In [13]:
data = eliminar_variables_pd(df= data, variables= variables_ml)

In [14]:
data.shape

(799869, 48)

## Sustituimos Valores Nulos:

In [15]:
data = sustituir_nulos_pd(df= data, variable= 'lista_mex', text= 'Sin Registros')
data = sustituir_nulos_pd(df= data, variable= 'estado_defuncion_residencia', text= 'Sin Registros')

## Corroboramos Ausencia de Valores Nulos:

In [16]:
data.isnull().sum().sort_values(ascending=False).head(10)

tloc_ocurr    0
causa_def     0
lista_mex     0
sexo          0
afromex       0
conindig      0
lengua        0
cve_lengua    0
nacionalid    0
nacesp_cve    0
dtype: int64

## Reducimos el Conjunto de Datos:

In [17]:
data = data[data['tipo_defun']=='Homicidio (Agresión)']

In [18]:
data['causa_def'].value_counts()

causa_def
Agresión con disparo de otras armas de fuego, y las no especificadas en calles y carreteras        11708
Agresión con disparo de otras armas de fuego, y las no especificadas en lugar no especificado       4431
Agresión con disparo de otras armas de fuego, y las no especificadas en vivienda                    2622
Agresión con disparo de otras armas de fuego, y las no especificadas en otro lugar especificado     2023
Agresión por medios no especificados en lugar no especificado                                       1385
                                                                                                   ...
Agresión con fuerza corporal en área industrial y de la construcción                                   1
Agresión con plaguicidas en granja                                                                     1
Agresión con objeto romo o sin filo en institución residencial                                         1
Agresión por colisión de vehículo de motor en granja                                                   1
Agresión con drogas, medicamentos y sustancias biológicas en vivienda                                  1
Name: count, Length: 116, dtype: int64

## Creamos la Variable Clasificadora:

In [19]:
data['feminmuj'] = ['Sí' if tipo_defun == 'Homicidio (Agresión)' and sexo == 'Mujer' else 'No' 
                          for tipo_defun, sexo in zip(data['tipo_defun'], data['sexo'])]

data

,tloc_ocurr,causa_def,lista_mex,sexo,afromex,conindig,lengua,cve_lengua,nacionalid,nacesp_cve,...,minutos,capitulo,lista1,area_ur,edad_agru,dia_cert,mes_cert,estado_defuncion_registrada,estado_defuncion_residencia,feminmuj
814,500 000 a 999 999 habitantes,Agresión con objeto cortante en lugar no espec...,Agresiones (homicidios),Hombre,No,No,No,No aplica,Mexicana,Mexicana (no especificado de Entidad Federativa),...,Trece minutos,Factores suplementarios relacionados con causa...,Agresiones,Urbana,De 20 a 24 años,Dieciséis días,Enero,Aguascalientes,Aguascalientes,No
847,500 000 a 999 999 habitantes,"Agresión con disparo de otras armas de fuego, ...",Agresiones (homicidios),Hombre,No,No,No,No aplica,Mexicana,Mexicana (no especificado de Entidad Federativa),...,Treinta minutos,Factores suplementarios relacionados con causa...,Agresiones,Urbana,De 25 a 29 años,Siete días,Marzo,Aguascalientes,Aguascalientes,No
888,10 000 a 14 999 habitantes,"Agresión con disparo de otras armas de fuego, ...",Agresiones (homicidios),Mujer,No,No,No,No aplica,Mexicana,Mexicana (no especificado de Entidad Federativa),...,No especificado,Factores suplementarios relacionados con causa...,Agresiones,Urbana,De 15 a 19 años,Veinticuatro días,Marzo,Aguascalientes,Aguascalientes,Sí
889,500 000 a 999 999 habitantes,Agresión con objeto romo o sin filo en calles ...,Agresiones (homicidios),Hombre,No,No,No,No aplica,Mexicana,Mexicana (no especificado de Entidad Federativa),...,Nueve minutos,Factores suplementarios relacionados con causa...,Agresiones,Urbana,De 40 a 44 años,Veintiséis días,Marzo,Aguascalientes,Aguascalientes,No
900,500 000 a 999 999 habitantes,"Agresión con disparo de otras armas de fuego, ...",Agresiones (homicidios),Mujer,No,No,No,No aplica,Mexicana,Mexicana (no especificado de Entidad Federativa),...,No especificado,Factores suplementarios relacionados con causa...,Agresiones,Urbana,De 55 a 59 años,Tres días,Enero,Aguascalientes,Aguascalientes,Sí
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799848,100 000 a 249 999 habitantes,Agresión con objeto cortante en lugar no espec...,Agresiones (homicidios),Hombre,No,No,Sí,No especificado,Mexicana,Mexicana (no especificado de Entidad Federativa),...,No especificado,Factores suplementarios relacionados con causa...,Agresiones,Rural,De 15 a 19 años,No especificado,Septiembre,Zacatecas,Zacatecas,No
799849,100 000 a 249 999 habitantes,"Agresión con disparo de otras armas de fuego, ...",Agresiones (homicidios),Mujer,No,No,Sí,No especificado,Mexicana,Mexicana (no especificado de Entidad Federativa),...,No especificado,Factores suplementarios relacionados con causa...,Agresiones,Urbana,De 20 a 24 años,Veinticuatro días,Diciembre,Zacatecas,Zacatecas,Sí
799850,100 000 a 249 999 habitantes,"Agresión con disparo de otras armas de fuego, ...",Agresiones (homicidios),Hombre,No,No,Sí,No especificado,Mexicana,Mexicana (no especificado de Entidad Federativa),...,No especificado,Factores suplementarios relacionados con causa...,Agresiones,Urbana,De 20 a 24 años,Veintinueve días,Diciembre,Zacatecas,Zacatecas,No
799851,100 000 a 249 999 habitantes,"Agresión con disparo de otras armas de fuego, ...",Agresiones (homicidios),Hombre,No,No,Sí,No especificado,Mexicana,Mexicana (no especificado de Entidad Federativa),...,No especificado,Factores suplementarios relacionados con causa...,Agresiones,Urbana,De 40 a 44 años,Treinta y un días,Diciembre,Zacatecas,Zacatecas,No
799852,1 000 a 1 999 habitantes,"Agresión por ahorcamiento, estrangulamiento y ...",Agresiones (homicidios),Hombre,No,No,Sí,No especificado,Mexicana,Mexicana (no especificado de Entidad Federativa),...,No especificado,Factores suplementarios relacionados con causa...,Agresiones,Urbana,De 25 a 29 años,No especificado,Julio,Zacatecas,Zacatecas,No

In [20]:
data = data.drop(['tipo_defun', 'lista_mex', 'lista1'], axis=1)
data

,tloc_ocurr,causa_def,sexo,afromex,conindig,lengua,cve_lengua,nacionalid,nacesp_cve,edad,...,horas,minutos,capitulo,area_ur,edad_agru,dia_cert,mes_cert,estado_defuncion_registrada,estado_defuncion_residencia,feminmuj
814,500 000 a 999 999 habitantes,Agresión con objeto cortante en lugar no espec...,Hombre,No,No,No,No aplica,Mexicana,Mexicana (no especificado de Entidad Federativa),Veintiún años,...,Quince horas,Trece minutos,Factores suplementarios relacionados con causa...,Urbana,De 20 a 24 años,Dieciséis días,Enero,Aguascalientes,Aguascalientes,No
847,500 000 a 999 999 habitantes,"Agresión con disparo de otras armas de fuego, ...",Hombre,No,No,No,No aplica,Mexicana,Mexicana (no especificado de Entidad Federativa),Veintiocho años,...,Veintiún horas,Treinta minutos,Factores suplementarios relacionados con causa...,Urbana,De 25 a 29 años,Siete días,Marzo,Aguascalientes,Aguascalientes,No
888,10 000 a 14 999 habitantes,"Agresión con disparo de otras armas de fuego, ...",Mujer,No,No,No,No aplica,Mexicana,Mexicana (no especificado de Entidad Federativa),Dieciocho años,...,No especificada,No especificado,Factores suplementarios relacionados con causa...,Urbana,De 15 a 19 años,Veinticuatro días,Marzo,Aguascalientes,Aguascalientes,Sí
889,500 000 a 999 999 habitantes,Agresión con objeto romo o sin filo en calles ...,Hombre,No,No,No,No aplica,Mexicana,Mexicana (no especificado de Entidad Federativa),Cuarenta años,...,Nueve horas,Nueve minutos,Factores suplementarios relacionados con causa...,Urbana,De 40 a 44 años,Veintiséis días,Marzo,Aguascalientes,Aguascalientes,No
900,500 000 a 999 999 habitantes,"Agresión con disparo de otras armas de fuego, ...",Mujer,No,No,No,No aplica,Mexicana,Mexicana (no especificado de Entidad Federativa),Cincuenta y cinco años,...,No especificada,No especificado,Factores suplementarios relacionados con causa...,Urbana,De 55 a 59 años,Tres días,Enero,Aguascalientes,Aguascalientes,Sí
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799848,100 000 a 249 999 habitantes,Agresión con objeto cortante en lugar no espec...,Hombre,No,No,Sí,No especificado,Mexicana,Mexicana (no especificado de Entidad Federativa),Dieciocho años,...,No especificada,No especificado,Factores suplementarios relacionados con causa...,Rural,De 15 a 19 años,No especificado,Septiembre,Zacatecas,Zacatecas,No
799849,100 000 a 249 999 habitantes,"Agresión con disparo de otras armas de fuego, ...",Mujer,No,No,Sí,No especificado,Mexicana,Mexicana (no especificado de Entidad Federativa),Veinticuatro años,...,No especificada,No especificado,Factores suplementarios relacionados con causa...,Urbana,De 20 a 24 años,Veinticuatro días,Diciembre,Zacatecas,Zacatecas,Sí
799850,100 000 a 249 999 habitantes,"Agresión con disparo de otras armas de fuego, ...",Hombre,No,No,Sí,No especificado,Mexicana,Mexicana (no especificado de Entidad Federativa),Veinte años,...,No especificada,No especificado,Factores suplementarios relacionados con causa...,Urbana,De 20 a 24 años,Veintinueve días,Diciembre,Zacatecas,Zacatecas,No
799851,100 000 a 249 999 habitantes,"Agresión con disparo de otras armas de fuego, ...",Hombre,No,No,Sí,No especificado,Mexicana,Mexicana (no especificado de Entidad Federativa),Cuarenta años,...,No especificada,No especificado,Factores suplementarios relacionados con causa...,Urbana,De 40 a 44 años,Treinta y un días,Diciembre,Zacatecas,Zacatecas,No
799852,1 000 a 1 999 habitantes,"Agresión por ahorcamiento, estrangulamiento y ...",Hombre,No,No,Sí,No especificado,Mexicana,Mexicana (no especificado de Entidad Federativa),Veintiséis años,...,No especificada,No especificado,Factores suplementarios relacionados con causa...,Urbana,De 25 a 29 años,No especificado,Julio,Zacatecas,Zacatecas,No

## Convertimos a Numérica la Variable Objetivo:

In [21]:
data['feminmuj'].replace(to_replace='Sí', value = 1, inplace=True)
data['feminmuj'].replace(to_replace='No', value = 0, inplace=True)

In [22]:
data.head()

,tloc_ocurr,causa_def,sexo,afromex,conindig,lengua,cve_lengua,nacionalid,nacesp_cve,edad,...,horas,minutos,capitulo,area_ur,edad_agru,dia_cert,mes_cert,estado_defuncion_registrada,estado_defuncion_residencia,feminmuj
814,500 000 a 999 999 habitantes,Agresión con objeto cortante en lugar no espec...,Hombre,No,No,No,No aplica,Mexicana,Mexicana (no especificado de Entidad Federativa),Veintiún años,...,Quince horas,Trece minutos,Factores suplementarios relacionados con causa...,Urbana,De 20 a 24 años,Dieciséis días,Enero,Aguascalientes,Aguascalientes,0
847,500 000 a 999 999 habitantes,"Agresión con disparo de otras armas de fuego, ...",Hombre,No,No,No,No aplica,Mexicana,Mexicana (no especificado de Entidad Federativa),Veintiocho años,...,Veintiún horas,Treinta minutos,Factores suplementarios relacionados con causa...,Urbana,De 25 a 29 años,Siete días,Marzo,Aguascalientes,Aguascalientes,0
888,10 000 a 14 999 habitantes,"Agresión con disparo de otras armas de fuego, ...",Mujer,No,No,No,No aplica,Mexicana,Mexicana (no especificado de Entidad Federativa),Dieciocho años,...,No especificada,No especificado,Factores suplementarios relacionados con causa...,Urbana,De 15 a 19 años,Veinticuatro días,Marzo,Aguascalientes,Aguascalientes,1
889,500 000 a 999 999 habitantes,Agresión con objeto romo o sin filo en calles ...,Hombre,No,No,No,No aplica,Mexicana,Mexicana (no especificado de Entidad Federativa),Cuarenta años,...,Nueve horas,Nueve minutos,Factores suplementarios relacionados con causa...,Urbana,De 40 a 44 años,Veintiséis días,Marzo,Aguascalientes,Aguascalientes,0
900,500 000 a 999 999 habitantes,"Agresión con disparo de otras armas de fuego, ...",Mujer,No,No,No,No aplica,Mexicana,Mexicana (no especificado de Entidad Federativa),Cincuenta y cinco años,...,No especificada,No especificado,Factores suplementarios relacionados con causa...,Urbana,De 55 a 59 años,Tres días,Enero,Aguascalientes,Aguascalientes,1

In [23]:
data = data[data['sexo'] != 'No especificado']

In [24]:
data.shape

(31983, 46)

## Separar variables predictoras y objetivo ANTES del dummificado

In [25]:
X = data.drop(['sexo', 'feminmuj'], axis=1)
y = data['feminmuj']

## Dummificamos las Variables:

In [26]:
X = pd.get_dummies(X, drop_first=True)

## Escalamos los Datos:

In [27]:
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=X.columns)

## Aplicamos SMOTE para Balancear:

In [29]:
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X_scaled, y)

In [30]:
print(f"Datos originales - Clase 0: {sum(y==0)}, Clase 1: {sum(y==1)}")
print(f"Datos balanceados - Clase 0: {sum(y_resampled==0)}, Clase 1: {sum(y_resampled==1)}")

Datos originales - Clase 0: 28244, Clase 1: 3739
Datos balanceados - Clase 0: 28244, Clase 1: 28244

## Dividimos el Conjunto de Datos:

In [31]:
X_train, X_test, y_train, y_test = train_test_split(
    X_resampled, y_resampled, test_size=0.2, random_state=42, stratify=y_resampled
)

## Método 1: Scikit-learn para métricas generales:

In [32]:
model_sklearn = LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)
model_sklearn.fit(X_train, y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

## Evaluamos el Modelo:

In [33]:
prediction_test = model_sklearn.predict(X_test)
print("\n===== EVALUACIÓN DEL MODELO =====")
print("Accuracy:", accuracy_score(y_test, prediction_test))
print("Balanced Accuracy:", balanced_accuracy_score(y_test, prediction_test))
print(classification_report(y_test, prediction_test))

===== EVALUACIÓN DEL MODELO =====
Accuracy: 0.7580102673039476
Balanced Accuracy: 0.7580102673039476
              precision    recall  f1-score   support

           0       0.78      0.72      0.75      5649
           1       0.74      0.80      0.77      5649

    accuracy                           0.76     11298
   macro avg       0.76      0.76      0.76     11298
weighted avg       0.76      0.76      0.76     11298

## Método 2: Statsmodels para obtener valores de p:

In [34]:
print("\n===== CALCULANDO VALORES DE P =====")

===== CALCULANDO VALORES DE P =====

## Agregamos Constantes para Statmodels:

In [35]:
X_train_sm = sm.add_constant(X_train)
X_test_sm = sm.add_constant(X_test)

## Ajustamos Modelo con Statmodels:

In [36]:
model_sm = sm.Logit(y_train, X_train_sm)
result_sm = model_sm.fit(disp=0)

LinAlgError: Singular matrix

## Obtenemos Estadísticas Completas:

In [ ]:
print("Modelo ajustado exitosamente!")
print(f"Número de variables: {len(X_train.columns)}")
print(f"Número de observaciones: {len(X_train)}")

## Método 3: Calcular valores de p manualmente usando Wald test:

In [37]:
def calculate_p_values_manual(model_sklearn, X_train):
    """
    Calcula valores de p usando el test de Wald
    """
    # Obtener coeficientes y matriz de covarianza estimada
    coef = model_sklearn.coef_[0]
    
    # Calcular matriz de información de Fisher aproximada
    # Usar predicciones del modelo entrenado
    y_pred_proba = model_sklearn.predict_proba(X_train)[:, 1]
    
    # Weights para la matriz de información
    weights = y_pred_proba * (1 - y_pred_proba)
    
    # Matriz de información de Fisher
    X_weighted = X_train.values * weights.reshape(-1, 1)
    fisher_info = np.dot(X_train.values.T, X_weighted)
    
    # Intentar invertir la matriz (agregar regularización si es necesario)
    try:
        cov_matrix = np.linalg.inv(fisher_info)
    except np.linalg.LinAlgError:
        # Si la matriz es singular, agregar regularización
        cov_matrix = np.linalg.inv(fisher_info + np.eye(fisher_info.shape[0]) * 1e-8)
    
    # Errores estándar
    std_errors = np.sqrt(np.diag(cov_matrix))
    
    # Estadística de Wald
    wald_stats = coef / std_errors
    
    # Valores de p (distribución normal estándar, test de dos colas)
    p_values = 2 * (1 - chi2.cdf(wald_stats**2, df=1))
    
    return p_values, std_errors, wald_stats

## Calculamos Valores de p:

In [38]:
p_values, std_errors, wald_stats = calculate_p_values_manual(model_sklearn, X_train)

## Creamos Dataframe con los Resultados:

In [39]:
results_df = pd.DataFrame({
    'Variable': X_train.columns,
    'Coeficiente': model_sklearn.coef_[0],
    'Error_Estandar': std_errors,
    'Estadistica_Wald': wald_stats,
    'Valor_P': p_values,
    'Odds_Ratio': np.exp(model_sklearn.coef_[0])
})

## Ordenamos Valores de p:

In [40]:
results_df = results_df.sort_values('Valor_P')

In [41]:
print("\n===== RESULTADOS CON VALORES DE P =====")
print("Variables más significativas (p < 0.05):")
significant_vars = results_df[results_df['Valor_P'] < 0.05]
print(f"Número de variables significativas: {len(significant_vars)}")

===== RESULTADOS CON VALORES DE P =====
Variables más significativas (p < 0.05):
Número de variables significativas: 101

## Mostramos las 20 Variables más Significativas:

In [42]:
print("\nTop 20 variables más significativas:")
print(significant_vars.head(20).to_string(index=False))

Top 20 variables más significativas:
                                                                                                                                       Variable  Coeficiente  Error_Estandar  Estadistica_Wald      Valor_P  Odds_Ratio
                                                                                               ocupacion_Profesores y especialistas en docencia     3.202788        0.262560         12.198297 0.000000e+00   24.601023
                       ocupacion_Otros comerciantes, empleados en ventas y agentes de ventas en establecimientos, no clasificados anteriormente     2.275981        0.217677         10.455752 0.000000e+00    9.737469
                                                                                          ocupacion_Ocupaciones insuficientemente especificadas     1.878127        0.158331         11.862045 0.000000e+00    6.541244
ocupacion_Supervisores de personal de apoyo administrativo, secretarias, capturistas, cajeros y trabajadores de control de archivo y transporte     2.555733        0.231940         11.018965 0.000000e+00   12.880742
                                                                    ocupacion_Enfermeras, técnicos en medicina y trabajadores de apoyo en salud     3.329452        0.277580         11.994546 0.000000e+00   27.923028
                                                                                                                             edo_civil_Viudo(a)     1.498952        0.119558         12.537405 0.000000e+00    4.476993
                                                                                                     ocupacion_Comerciantes en establecimientos     2.215338        0.159183         13.916940 0.000000e+00    9.164503
                                                                                                                         sitio_ocur_Vía pública    -0.564084        0.065955         -8.552613 0.000000e+00    0.568881
                                                                                      ocupacion_Trabajadores en cuidados personales y del hogar     2.206003        0.204037         10.811756 0.000000e+00    9.079349
                                                                                                                               mes_cert_Febrero    -0.661998        0.071988         -9.195995 0.000000e+00    0.515820
              ocupacion_Trabajadores en la preparación y servicio de alimentos y bebidas, así como en servicios de esparcimiento y de hotelería     1.752407        0.199846          8.768802 0.000000e+00    5.768468
                                                                     ocupacion_Trabajadores en la extracción y la edificación de construcciones    -2.612055        0.274860         -9.503206 0.000000e+00    0.073384
                                                  ocupacion_Trabajadores domésticos, de limpieza, planchadores y otros trabajadores de limpieza     2.192807        0.179043         12.247360 0.000000e+00    8.960329
                                                                                 ocupacion_Trabajadores en servicios de protección y vigilancia     1.421165        0.179100          7.935025 4.218847e-15    4.141942
                                                                                              ocupacion_Empleados de ventas en establecimientos     1.676665        0.221552          7.567798 7.593925e-14    5.347690
                                                                                                                          sitio_ocur_Otro lugar    -0.491433        0.066024         -7.443229 1.965095e-13    0.611749
                                                                                                                 sitio_ocur_Secretaría de salud    -0.673262        0.093291         -7.216821 1.064260e-12    0.510042
                                                                                   ocupacion_Médicos, enfermeras y otros especialistas en salud     2.298952        0.324315          7.088640 2.708722e-12    9.963733
                                                                                                                     sitio_ocur_No especificado    -0.547399        0.079435         -6.891147 1.106892e-11    0.578452
                                                                                                                          horas_Veintidós horas    -0.636785        0.095310         -6.681181 4.740475e-11    0.528990

In [68]:
data['lugar_ocur'].value_counts()

lugar_ocur
Calle o carretera (vía pública)    15586
Se ignora                           7361
Vivienda particular                 3914
Otro                                3322
Área comercial o de servicios        856
Granja (rancho o parcela)            587
Área industrial (taller)             118
Vivienda colectiva                    93
Áreas deportivas                      80
Escuela u oficina pública             66
Name: count, dtype: int64

In [77]:
results_df[results_df['Variable'] == 'edo_civil_Viudo(a)']

,Variable,Coeficiente,Error_Estandar,Estadistica_Wald,Valor_P,Odds_Ratio
421,edo_civil_Viudo(a),1.498952,0.119558,12.537405,0.0,4.476993

In [76]:
results_df[results_df['Variable'] == 'estado_defuncion_residencia_Sinaloa']

,Variable,Coeficiente,Error_Estandar,Estadistica_Wald,Valor_P,Odds_Ratio
707,estado_defuncion_residencia_Sinaloa,1.184767,0.560199,2.114906,0.068876,3.269926

In [79]:
results_df.sort_values(by = 'Coeficiente', ascending=False).head(60)

,Variable,Coeficiente,Error_Estandar,Estadistica_Wald,Valor_P,Odds_Ratio
156,cve_lengua_Huichol,3.510928,1.792366,1.958823,1.002670e-01,33.479326
368,"ocupacion_Enfermeras, técnicos en medicina y t...",3.329452,0.277580,11.994546,0.000000e+00,27.923028
387,ocupacion_Profesores y especialistas en docencia,3.202788,0.262560,12.198297,0.000000e+00,24.601023
358,ocupacion_Busca trabajo,2.643334,0.630619,4.191651,5.538633e-05,14.060002
388,ocupacion_Supervisores de personal de apoyo ad...,2.555733,0.231940,11.018965,0.000000e+00,12.880742
372,"ocupacion_Médicos, enfermeras y otros especial...",2.298952,0.324315,7.088640,2.708722e-12,9.963733
378,"ocupacion_Otros comerciantes, empleados en ven...",2.275981,0.217677,10.455752,0.000000e+00,9.737469
359,ocupacion_Comerciantes en establecimientos,2.215338,0.159183,13.916940,0.000000e+00,9.164503
397,ocupacion_Trabajadores en cuidados personales ...,2.206003,0.204037,10.811756,0.000000e+00,9.079349
394,"ocupacion_Trabajadores domésticos, de limpieza...",2.192807,0.179043,12.247360,0.000000e+00,8.960329
129,causa_def_Agresión por otros medios especifica...,2.186753,0.890634,2.455278,2.815516e-02,8.906250
440,"par_agre_Esposo, Cónyuge",2.152401,2549.882449,0.000844,1.998653e+00,8.605495
216,nacesp_cve_República del Ecuador,2.142093,8.950718,0.239321,1.621714e+00,8.517249
357,ocupacion_Ayudantes en la preparación de alime...,2.120873,0.597334,3.550567,7.688048e-04,8.338416
161,cve_lengua_Mazateco,1.953864,1.709235,1.143122,5.059760e-01,7.055901
441,par_agre_Ex esposo,1.940057,2549.882483,0.000761,1.998786e+00,6.959147
376,ocupacion_Ocupaciones insuficientemente especi...,1.878127,0.158331,11.862045,0.000000e+00,6.541244
400,ocupacion_Trabajadores en la preparación y ser...,1.752407,0.199846,8.768802,0.000000e+00,5.768468
459,vio_fami_Sí,1.704899,4126.066531,0.000413,1.999341e+00,5.500828
113,causa_def_Agresión por empujón desde un lugar ...,1.678856,1.008448,1.664792,1.919087e-01,5.359422
367,ocupacion_Empleados de ventas en establecimientos,1.676665,0.221552,7.567798,7.593925e-14,5.347690
364,"ocupacion_Directores y gerentes de ventas, res...",1.671300,0.725446,2.303824,4.246504e-02,5.319079
436,"par_agre_Concubino, compañero",1.648926,2549.882398,0.000647,1.998968e+00,5.201391
708,estado_defuncion_residencia_Sonora,1.573194,0.565521,2.781849,1.081002e-02,4.822026
380,ocupacion_Otros operadores de maquinaria indus...,1.511780,0.244131,6.192496,1.184378e-09,4.534794
421,edo_civil_Viudo(a),1.498952,0.119558,12.537405,0.000000e+00,4.476993
353,ocupacion_Auxiliares y técnicos en ciencias ec...,1.491951,0.325372,4.585364,9.063919e-06,4.445761
375,ocupacion_No trabaja,1.456738,5508.043211,0.000264,1.999578e+00,4.291935
496,derechohab_Reportado como equivalente al Segur...,1.437656,0.690324,2.082582,7.457870e-02,4.210814
402,ocupacion_Trabajadores en servicios de protecc...,1.421165,0.179100,7.935025,4.218847e-15,4.141942
265,edad_Ochenta años,1.417102,4100.350330,0.000346,1.999448e+00,4.125148
386,ocupacion_Profesionistas en ciencias económico...,1.380250,0.212799,6.486180,1.760796e-10,3.975897
370,ocupacion_Funcionarios y altas autoridades de ...,1.261015,0.538008,2.343859,3.817072e-02,3.529000
366,ocupacion_Directores y gerentes en servicios f...,1.243679,0.701850,1.772001,1.527888e-01,3.468349
108,"causa_def_Agresión por ahorcamiento, estrangul...",1.234485,0.843160,1.464117,2.863238e-01,3.436607
490,derechohab_IMSS BIENESTAR,1.225154,0.428637,2.858255,8.519553e-03,3.404689
707,estado_defuncion_residencia_Sinaloa,1.184767,0.560199,2.114906,6.887599e-02,3.269926
97,causa_def_Agresión por ahogamiento y sumersión...,1.183095,1.712777,0.690747,9.794491e-01,3.264463
476,donador_Sí,1.176509,0.356385,3.301230,1.925239e-03,3.243032
383,ocupacion_Otros trabajadores auxiliares en act...,1.146991,0.253939,4.516805,1.255594e-05,3.148705
64,"causa_def_Agresión con humo, fuego y llamas en...",1.137816,0.819046,1.389197,3.295460e-01,3.119947
685,estado_defuncion_residencia_Campeche,1.129943,0.803002,1.407148,3.187669e-01,3.095479
134,causa_def_Negligencia y abandono por otra pers...,1.114185,1.704869,0.653531,1.026828e+00,3.047084
251,edad_Doce años,1.105939,2294.251149,0.000482,1.999231e+00,3.022061
568,minutos_Treinta y siete minutos,1.081937,0.383437,2.821682,9.554498e-03,2.950390
107,"causa_def_Agresión por ahorcamiento, estrangul...",1.055414,0.685558,1.539497,2.473662e-01,2.873164
401,ocupacion_Trabajadores en servicios de alquiler,1.049742,0.690797,1.519609,2.572185e-01,2.856913
60,"causa_def_Agresión con humo, fuego y llamas en...",1.045302,2988.207427,0.000350,1.999442e+00,2.844258
275,edad_Ocho años,1.032057,4166.024385,0.000248,1.999605e+00,2.806834
94,causa_def_Agresión con productos químicos y su...,1.018654,0.957565,1.063796,5.748427e-01,2.769463
696,estado_defuncion_residencia_Michoacán,0.999237,0.522390,1.912818,1.115428e-01,2.716208
116,causa_def_Agresión por empujón desde un lugar ...,0.996271,1.257526,0.792247,8.564334e-01,2.708164
379,"ocupacion_Otros directores, funcionarios, gere...",0.947635,0.264376,3.584419,6.756586e-04,2.579603
104,"causa_def_Agresión por ahorcamiento, estrangul...",0.947190,1.628033,0.581801,1.121402e+00,2.578455
667,estado_defuncion_registrada_México,0.922573,0.514301,1.793841,1.456772e-01,2.515756
53,causa_def_Agresión con fuerza corporal en vivi...,0.880422,1.021657,0.861760,7.776397e-01,2.411918
298,edad_Setenta y ocho años,0.880039,4100.350653,0.000215,1.999658e+00,2.410994
296,edad_Setenta y dos años,0.878749,4100.352119,0.000214,1.999658e+00,2.407886
66,"causa_def_Agresión con humo, fuego y llamas en...",0.867560,5.281044,0.164278,1.739024e+00,2.381094
659,estado_defuncion_registrada_Colima,0.837191,0.528174,1.585066,2.259028e-01,2.309870

In [ ]:
significant_vars.sort

,Variable,Coeficiente,Error_Estandar,Estadistica_Wald,Valor_P,Odds_Ratio
387,ocupacion_Profesores y especialistas en docencia,3.202788,0.262560,12.198297,0.000000e+00,24.601023
378,"ocupacion_Otros comerciantes, empleados en ven...",2.275981,0.217677,10.455752,0.000000e+00,9.737469
376,ocupacion_Ocupaciones insuficientemente especi...,1.878127,0.158331,11.862045,0.000000e+00,6.541244
388,ocupacion_Supervisores de personal de apoyo ad...,2.555733,0.231940,11.018965,0.000000e+00,12.880742
368,"ocupacion_Enfermeras, técnicos en medicina y t...",3.329452,0.277580,11.994546,0.000000e+00,27.923028
421,edo_civil_Viudo(a),1.498952,0.119558,12.537405,0.000000e+00,4.476993
359,ocupacion_Comerciantes en establecimientos,2.215338,0.159183,13.916940,0.000000e+00,9.164503
488,sitio_ocur_Vía pública,-0.564084,0.065955,-8.552613,0.000000e+00,0.568881
397,ocupacion_Trabajadores en cuidados personales ...,2.206003,0.204037,10.811756,0.000000e+00,9.079349
643,mes_cert_Febrero,-0.661998,0.071988,-9.195995,0.000000e+00,0.515820
400,ocupacion_Trabajadores en la preparación y ser...,1.752407,0.199846,8.768802,0.000000e+00,5.768468
399,ocupacion_Trabajadores en la extracción y la e...,-2.612055,0.274860,-9.503206,0.000000e+00,0.073384
394,"ocupacion_Trabajadores domésticos, de limpieza...",2.192807,0.179043,12.247360,0.000000e+00,8.960329
402,ocupacion_Trabajadores en servicios de protecc...,1.421165,0.179100,7.935025,4.218847e-15,4.141942
367,ocupacion_Empleados de ventas en establecimientos,1.676665,0.221552,7.567798,7.593925e-14,5.347690
482,sitio_ocur_Otro lugar,-0.491433,0.066024,-7.443229,1.965095e-13,0.611749
486,sitio_ocur_Secretaría de salud,-0.673262,0.093291,-7.216821,1.064260e-12,0.510042
372,"ocupacion_Médicos, enfermeras y otros especial...",2.298952,0.324315,7.088640,2.708722e-12,9.963733
480,sitio_ocur_No especificado,-0.547399,0.079435,-6.891147,1.106892e-11,0.578452
520,horas_Veintidós horas,-0.636785,0.095310,-6.681181,4.740475e-11,0.528990

Factores Asociados con Homicidios de Mujeres en México: Análisis de Regresión Logística de Datos Nacionales 2023

## Usar statsmodels como verificación (para subset de variables si es necesario):

In [ ]:
try:
    print("\n===== VERIFICACIÓN CON STATSMODELS =====")
    print("Resumen estadístico del modelo:")
    print(result_sm.summary2().tables[1].head(10))  # Mostrar solo las primeras 10 variables
    
    # Comparar algunos valores de p
    sm_pvalues = result_sm.pvalues[1:]  # Excluir constante
    manual_pvalues = p_values
    
    print(f"\nComparación de primeros 5 valores de p:")
    print("Variable\t\tManual\t\tStatsmodels")
    for i in range(min(5, len(sm_pvalues))):
        var_name = X_train.columns[i][:15]  # Truncar nombre
        print(f"{var_name}\t{manual_pvalues[i]:.6f}\t{sm_pvalues.iloc[i]:.6f}")
        
except Exception as e:
    print(f"Nota: Statsmodels no pudo procesar todas las variables: {str(e)}")

## Validación Cruzada:

In [ ]:
print("\n===== VALIDACIÓN CRUZADA =====")
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
accuracy_scores = []
balanced_acc_scores = []
f1_scores = []

for train_index, test_index in skf.split(X_resampled, y_resampled):
    X_train_fold, X_test_fold = X_resampled.iloc[train_index], X_resampled.iloc[test_index]
    y_train_fold, y_test_fold = y_resampled[train_index], y_resampled[test_index]
    
    model_sklearn.fit(X_train_fold, y_train_fold)
    y_pred_fold = model_sklearn.predict(X_test_fold)
    
    accuracy_scores.append(accuracy_score(y_test_fold, y_pred_fold))
    balanced_acc_scores.append(balanced_accuracy_score(y_test_fold, y_pred_fold))
    f1_scores.append(f1_score(y_test_fold, y_pred_fold))

In [ ]:
print(f"Accuracy promedio: {np.mean(accuracy_scores):.4f}")
print(f"Balanced Accuracy promedio: {np.mean(balanced_acc_scores):.4f}")
print(f"F1-score promedio: {np.mean(f1_scores):.4f}")

## Función para el Análisis de Variables Específicas:

In [ ]:
def analizar_variables_especificas(results_df, keywords=None):
    """
    Analiza variables específicas basadas en palabras clave
    """
    if keywords is None:
        keywords = ['edad', 'estado', 'municipio', 'escolaridad', 'ocupacion']
    
    print(f"\n===== ANÁLISIS DE VARIABLES ESPECÍFICAS =====")
    for keyword in keywords:
        matching_vars = results_df[results_df['Variable'].str.contains(keyword, case=False, na=False)]
        if len(matching_vars) > 0:
            print(f"\nVariables relacionadas con '{keyword}':")
            print(matching_vars[['Variable', 'Coeficiente', 'Valor_P', 'Odds_Ratio']].head(10).to_string(index=False))

In [ ]:
analizar_variables_especificas(results_df)

In [ ]:
print(f"\n===== RESUMEN FINAL =====")
print(f"Total de variables en el modelo: {len(results_df)}")
print(f"Variables significativas (p < 0.05): {len(results_df[results_df['Valor_P'] < 0.05])}")
print(f"Variables altamente significativas (p < 0.01): {len(results_df[results_df['Valor_P'] < 0.01])}")
print(f"Variable más significativa: {results_df.iloc[0]['Variable']} (p = {results_df.iloc[0]['Valor_P']:.2e})")